# Embeddings
embedding-provider: openai
embedding-model: text-embedding-3-small
tokens-per-chunk: 800
chunks-per-batch: 2000

# Vector store
vector-store-provider: pinecone
pinecone-index-name: sage
hybrid-retrieval: true

# LLM
llm-provider: openai
llm-model: gpt-4o

# Reranking
reranker-provider: nvidia
